alias ls='eza --icons'
alias cat='bat'
alias vim='nvim'

alias gl='git log'
alias gb='git branch'
alias gs='git status'
alias gr='git restore'
alias gd='git diff'
alias gpl='git pull'
alias gfc='git fetch'
alias gswc='git switch --create'
alias gpsc='git push origin HEAD'
alias gpsuc='git push -u origin HEAD'
