brew "ghq"
brew "graphviz"
brew "mas"
brew "nodebrew"
brew "peco"
brew "stow"
brew "starship"
brew "tig"
brew "tmux"

tap "homebrew/cask-fonts"

cask "alfred"
cask "bettertouchtool"
cask "dash"
cask "deepl"
cask "discord"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "keycastr"
cask "meetingbar"
cask "postman"
cask "proxyman"
cask "slack"
cask "visual-studio-code"
cask "xcodes"
cask "1password"

mas "BetterSnapTool", id: 417375580
mas "Kindle", id: 405399194
