[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && npm install"'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_disable_lsp = 1
  let g:ale_lint_on_text_changed = 1
  let g:ale_sign_error = '🚨'
  let g:ale_sign_warning = '⚠️'
'''

[[plugins]]
repo = 'tpope/vim-surround'
